services:
  - type: web
    name: vexel-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: starter
    disk:
      name: vexel-sqlite
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: Vexel API
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: LOG_CHANNEL
        value: stderr

  - type: web
    name: vexel-web
    env: docker
    dockerfilePath: ./web/Dockerfile
    dockerContext: ./web
    plan: starter
    envVars:
      - key: API_BASE_URL
        sync: false
