services:
  - type: web
    name: vexel
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    disk:
      name: vexel-sqlite
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: Vexel API
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/data/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: API_BASE_URL
        value: /api/v1
